MODEL_TYPE: vgg16
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
OPTIMIZER: sgd
LOSS_FUNCTION: categorical_crossentropy