artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_config:
    source: local
    username: hudaswati
    sourceURL: /home/huda/Downloads/Data.zip
    extract_to: artifacts/data_ingestion01

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras
  updated_base_model_path: artifacts/base_model/updated_base_model.keras

model_training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras

mlflow:
  mlflow_uri:

